encoding: utf-8

plugins:
  - jekyll-regex-replace

# SEOç›¸å…³ä¿¡æ¯
title: Lichium Blog
description: Lichiumçš„ä¸ªäººåšå®¢
author: Lichium
footerText: '~ Have a nice day ~'

# è¿™äº›ä¸è¦åŠ¨
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# åŸŸåé…ç½®
# baseurlé…ç½®,å¦‚æœç½‘ç«™éƒ¨ç½²åœ¨æ ¹ç›®å½•ä¸‹çš„å…¶ä»–ç›®å½•ä¸­ï¼Œè¯·è®¾ç½®ä¸º /ç›®å½•å
domainUrl: 'https://lichium.github.io'
baseurl: ''

# èœå•
# å¿…å¡«å­—æ®µ title: 'æ–‡æœ¬' url: 'é“¾æ¥'
# å¯é€‰å­—æ®µ target: '_blank' æ–°é¡µé¢æ‰“å¼€ 
menu:
  - title: é¦–é¡µ
    url: /
  - title: å½’ç±»
    url: /pages/categories.html
  - title: æœç´¢
    url: /pages/search.html
  - title: å…³äº
    url: /pages/about.html
  - title: ğŸš‡
    url: https://www.travellings.cn/go.html

# ç‚¹å‡»é¡µé¢æ–‡å­—å†’å‡ºç‰¹æ•ˆ,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extClickEffect: false

# Google Adsense,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
# _includes/ext-adsense.html é‡Œé¢ä¿®æ”¹ä¸ºè‡ªå·±çš„é…ç½®
extAdsense: false

# æ•°å­¦å…¬å¼æ”¯æŒï¼Œæ¯”è¾ƒå½±å“åŠ è½½é€Ÿåº¦,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extMath: true

# æ˜¾ç¤ºè®¿é—®é‡ç»Ÿè®¡ï¼Œç”±ä¸è’œå­æä¾›æœåŠ¡
extCount: false